f= open("uber_economics_processed_gui","w+")
g= open("uber_economics_processed_com","w+")
h= open("uber_economics_processed_yyy.txt","w+")
i= open("uber_economics_processed_combin.txt","w+")
#print('Filename:', filename, file=f) 
f.write("dgjlkjlkdfj")
g.write("sklgdjsdklgkljds")
h.write("sldfkldjfklsd")
i.write("jsdkljjkgl")
#g.write(print("gghhfhgfhgfhffg"))
#f.write("print("jmgjgjgj")")
#h.write(print(",kjjkgjjjvb"))
#i.write("print(",kjmnvnbv")")
