f= open("uber_economics_processed_gui","w+")
g= open("uber_economics_processed_com","w+")
h= open("uber_economics_processed_yyy.txt","w+")
i= open("uber_economics_processed_combin.txt","w+")
#f.write(uber_temp.collect())
#g.write("uber_temp.collect()")
#h.write(uber_temp.collect())
#i.write("uber_temp.collect()")
#g.write(print("gghhfhgfhgfhffg"))
#f.write("print("jmgjgjgj")")
#h.write(print(",kjjkgjjjvb"))
#i.write("print(",kjmnvnbv")")
